# terraform.tfvars 
instance_type        = "t2.micro"
tag                  = "kafka project instance"
location             = "us-east-1"
bucket_name          = "my-kafka-project-bucket11"
access_key           = "your-access-key"
secret_key           = "your-secret-key"
crawler_name         = "my-kafka-project-crawler"
crawler_description  = "Crawler for Kafka project data"
database_name        = "my-kafka-project-database"
database_description = "Database for storing Kafka project metadata"