-- SQL Script for creating the database table

CREATE TABLE rental_data_table (
    Prix NUMERIC(10, 2),
    Type_De_Bien INTEGER,
    Surface NUMERIC(10, 2),
    Nombre_De_Pieces NUMERIC(10, 2),
    Nombre_De_Chambres NUMERIC(10, 2),
    Nombre_De_Salles_De_Bain NUMERIC(10, 2),
    Etat_De_Location INTEGER,
    Etage INTEGER,
    Jardin BOOLEAN,
    Terrasse BOOLEAN,
    Garage BOOLEAN,
    Ascenseur BOOLEAN,
    Piscine BOOLEAN,
    Concierge BOOLEAN,
    Meuble BOOLEAN,
    Salon_Marocain BOOLEAN,
    Salon_Europeen BOOLEAN,
    Climatisation BOOLEAN,
    Securite BOOLEAN,
    Cuisine_equipee BOOLEAN,
    Refrigerateur BOOLEAN,
    Four BOOLEAN,
    TV BOOLEAN,
    Micro_ondes BOOLEAN,
    Animaux_domestiques_autorises BOOLEAN,
    Cheminee BOOLEAN,
    Ville_agadir BOOLEAN,
    Ville_bouskoura BOOLEAN,
    Ville_casablanca BOOLEAN,
    Ville_dar_bouazza BOOLEAN,
    Ville_kenitra BOOLEAN,
    Ville_marrakech BOOLEAN,
    Ville_mohammedia BOOLEAN,
    Ville_rabat BOOLEAN,
    Ville_sale BOOLEAN,
    Ville_tanger BOOLEAN
);
